name = "taxtools-taxmonitor-pro-api"
main = "src/index.js"
compatibility_date = "2026-03-02"

routes = [
  { pattern = "tools-api.taxmonitor.pro/*", zone_name = "taxmonitor.pro" }
]

migrations_dir = "./migrations"

[[d1_databases]]
binding = "DB"
database_name = "tax-tools-tax-monitor"
database_id = "e43ad11a-dd66-42fc-b162-b96a7295a079"

[[r2_buckets]]
binding = "R2_TAXTOOLS"
bucket_name = "taxtools-taxmonitor-pro"

[vars]

# Auth
TAXTOOLS_AUTH_BASE_URL = "https://tools-api.taxmonitor.pro"

# ClickUp
CLICKUP_ACCOUNTS_LIST_ID = "901710909567"
CLICKUP_SUPPORT_LIST_ID = "901710818377"

# Google Workspace
GOOGLE_CLIENT_EMAIL = "tax-monitor-worker@tax-monitor-pro.iam.gserviceaccount.com"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_WORKSPACE_USER_INFO = "info@taxmonitor.pro"
GOOGLE_WORKSPACE_USER_NO_REPLY = "no-reply@taxmonitor.pro"
GOOGLE_WORKSPACE_USER_SUPPORT = "support@taxmonitor.pro"

# Organization metadata
MY_ORGANIZATION_ADDRESS = "1175 Avocado Avenue Suite 101 PMB 1010"
MY_ORGANIZATION_BUSINESS_LOGO = "https://taxmonitor.pro/assets/logo.svg"
MY_ORGANIZATION_CITY = "El Cajon"
MY_ORGANIZATION_NAME = "Tax Monitor Pro"
MY_ORGANIZATION_STATE_PROVINCE = "CA"
MY_ORGANIZATION_ZIP = "92020"

# PayPal IDs
PAYPAL_CLIENT_ID = "AVtOtr3LiOz8PjZKHuPoxdeg5rOqSUxVPfm-iChUfTnY8smb1UuVXXiCnzYzNC-H--5_UjpxpgzDGzQ7"
PAYPAL_WEBHOOK_ID = "61844185M0758343H"
PAYPAL_ENV = "sandbox"
PAYPAL_WEBHOOKS_ENABLED = "true"
